backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "src/img/uploads" # Folder where user uploaded files should go
public_folder: "img/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, e.g., "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "pages"
    label: "Pages"
    folder: "site/content/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "URL", name: "url", widget: "string"}

  - name: "index"
    label: "Homepage"
    folder: "site/content"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "URL", name: "url", widget: "string"}

  - name: "tenets"
    label: "Tenets of Paul"
    folder: "site/content/tenents"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown", required: false}

  - name: "footer"
    label: "Footer Details"
    folder: "site/content/footer"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: false, default: "main"}
      - {label: "Copyright Info", name: "copyright", widget: "string", required: false}
      - {label: "Footer Slogan", name: "slogan", widget: "string", required: false}
      - name: "icons"
        label: "Social Media Icon"
        widget: "list"
        fields:
          - {label: "Service Name", name: "title", widget: "string", required: false}
          - {label: "Service URL", name: "url", widget: "string", required: false}
          - {label: "Service Icon Available Here: https://material.io/icons/", name: "icon", widget: "string", required: false, default: "explore"}
